# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travelmaster
    ports:
      - "5432:5432"

  sessionRedis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  #    volumes:
  #      - :/var/lib/postgresql/data

#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - APP_ENV=development
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    restart: on-failure